name: 🚀 Publish

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  build-linux:
    name: 🐧 Build Linux
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 📦 Install Linux dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: 🦀 Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: 💿 Install frontend dependencies
        run: npm ci

      - name: 🔨 Build Tauri
        run: npm run tauri build

      - name: 📦 Upload Linux to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: src-tauri/target/release/bundle/**/*.{AppImage,deb,rpm}
          tag: ${{ github.event.release.tag_name }}
          overwrite: true
          file_glob: true

  build-windows:
    name: 🪟 Build Windows
    runs-on: windows-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: 🦀 Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: 💿 Install frontend dependencies
        run: npm ci

      - name: 🔨 Build Tauri
        run: npm run tauri build

      - name: 📦 Upload Windows to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: src-tauri/target/release/bundle/**/*.{exe,msi}
          tag: ${{ github.event.release.tag_name }}
          overwrite: true
          file_glob: true