name: 🚀 Publish

on:
  release:
    types:
      - published

jobs:
  build-linux:
    name: 🐧 Build Linux
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 📦 Install Linux dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: 🦀 Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: 💿 Install frontend dependencies
        run: npm ci

      - name: 🔨 Build Tauri
        run: npm run tauri build

      - name: 📤 Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-linux
          path: |
            src-tauri/target/release/bundle/**

  build-windows:
    name: 🪟 Build Windows
    runs-on: windows-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: 🦀 Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: 💿 Install frontend dependencies
        run: npm ci

      - name: 🔨 Build Tauri
        run: npm run tauri build

      - name: 📤 Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-windows
          path: |
            src-tauri/target/release/bundle/**